[server]
maxUploadSize = 4000  # Increase max upload size to 4GB
maxMessageSize = 4194304000 # Increase max message size to 4GB

[theme]
primaryColor = "#ff6347"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"