[[pages]]
path = ".streamlit/1.0_ImportData.py"
name = "1. Read and process data"
icon = "ğŸ“¥"

[[pages]]
path = ".streamlit/1.1_Wavenumbers_raw.py"
name = "1.1 Wavenumbers per file (unmodified)"

[[pages]]
path = ".streamlit/1.2_Wavenumbers.py"
name = "1.2 Wavenumbers per file (rounded)"

[[pages]]
path = ".streamlit/1.3_UniqueWavenumbers.py"
name = "1.3 Unique wavenumbers"

[[pages]]
path = ".streamlit/1.4_ExperimentParameters.py"
name = "1.4 Experiment parameters"

[[pages]]
path = ".streamlit/2.0_BaselineCorrection.py"
name = "2. Baseline correction"
icon = "ğŸ“"

[[pages]]
path = ".streamlit/2.1_BaselineCorrectionFullRange.py"
name = "2.1 Baseline correction - full range"

[[pages]]
path = ".streamlit/3.0_CalculateDepletion.py"
name = "3. Data analysis"
icon = "ğŸ’ª"

[[pages]]
path = ".streamlit/4.0_Misc.py"
name = "4. Miscellaneous"
icon = "ğŸŒŒ"

[[pages]]
path = ".streamlit/4.1_MegaSum.py"
name = "4.1 MegaSum"

[[pages]]
path = ".streamlit/4.2_MegaSum-Baseline.py"
name = "4.2 MegaSum - baseline correction"

[[pages]]
path = ".streamlit/4.3_MegaSum-Integrate.py"
name = "4.3 MegaSum - integrate"